# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -rrequirements.txt

    - name: Run flake8
      run: |
        python -m flake8 -v

    - name: Run unittest
      run: |
        python -m unittest -v tests

    - name: Check supported_syntax
      run: |
        python -m transpiler examples/supported_syntax.pas

  build-docker:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        run: |
          docker build .
